# Sonar Rock vs. Mine Predictions

In [32]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score


In [33]:
# loading dataset to pandas dataframe
sonar_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Sonar Rock vs. Mine Predictions/sonar_data.csv',header=None)

In [34]:
sonar_data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [35]:
# number of rows and columns
sonar_data.shape

(208, 61)

In [36]:
sonar_data.describe()#describe the stat* of the data

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [37]:
sonar_data[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [38]:
sonar_data[60] = sonar_data[60].replace({'M':0,'R':1})

M ---> Mine
R ---> Rock 

In [39]:
sonar_data.groupby(60).mean()

0         1         2         3         4         5         6   \
60                                                                         
0   0.034989  0.045544  0.050720  0.064768  0.086715  0.111864  0.128359   
1   0.022498  0.030303  0.035951  0.041447  0.062028  0.096224  0.114180   

          7         8         9   ...        50        51        52        53  \
60                                ...                                           
0   0.149832  0.213492  0.251022  ...  0.019352  0.016014  0.011643  0.012185   
1   0.117596  0.137392  0.159325  ...  0.012311  0.010453  0.009640  0.009518   

          54        55        56        57        58        59  
60                                                              
0   0.009923  0.008914  0.007825  0.009060  0.008695  0.006930  
1   0.008567  0.007430  0.007814  0.006677  0.007078  0.006024  

[2 rows x 60 columns]

In [40]:
# seprate data and labels ()
X = sonar_data.drop(columns=60,axis=1)
Y = sonar_data[60]

In [41]:
print(X)
print(Y)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53   

splite data to train and test data

In [42]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=1)

In [43]:
print(X.shape,x_train.shape,x_test.shape)

(208, 60) (145, 60) (63, 60)


In [44]:
print(Y.shape,y_train.shape,y_test.shape)

(208,) (145,) (63,)


Model Training 

In [45]:
lg_model = LogisticRegression()
dt_model = DecisionTreeClassifier()
rf_model = RandomForestClassifier()
sv_model = SVC()
nb_model = GaussianNB()
kn_model = KNeighborsClassifier()

In [48]:
print(lg_model.fit(x_train,y_train))
print(dt_model.fit(x_train,y_train))
print(rf_model.fit(x_train,y_train))
print(sv_model.fit(x_train,y_train))
print(nb_model.fit(x_train,y_train))
print(kn_model.fit(x_train,y_train))

LogisticRegression()
DecisionTreeClassifier()
RandomForestClassifier()
SVC()
GaussianNB()
KNeighborsClassifier()


In [50]:
print(lg_model.score(x_test,y_test))
print(dt_model.score(x_test,y_test))
print(rf_model.score(x_test,y_test))
print(sv_model.score(x_test,y_test))
print(nb_model.score(x_test,y_test))
print(kn_model.score(x_test,y_test))

0.6666666666666666
0.746031746031746
0.8095238095238095
0.7777777777777778
0.7142857142857143
0.8253968253968254


In [52]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(lg_model,X,Y,cv=3))
print(cross_val_score(dt_model,X,Y,cv=3))
print(cross_val_score(rf_model,X,Y,cv=3))
print(cross_val_score(sv_model,X,Y,cv=3))
print(cross_val_score(nb_model,X,Y,cv=3))
print(cross_val_score(kn_model,X,Y,cv=3))

[0.5        0.60869565 0.50724638]
[0.5        0.56521739 0.5942029 ]
[0.51428571 0.66666667 0.5942029 ]
[0.42857143 0.55072464 0.44927536]
[0.51428571 0.62318841 0.44927536]
[0.48571429 0.57971014 0.36231884]


In [53]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X,Y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                    best_params
0                  svm    0.659350  {'C': 10, 'kernel': 'linear'}
1        random_forest    0.677816           {'n_estimators': 10}
2  logistic_regression    0.620674                       {'C': 1}

In [56]:
# Model Evaluation
# accuracy on traing data
X_train_prediction = lg_model.predict(x_train)
training_data_acc = accuracy_score(X_train_prediction,y_train)


In [58]:
print("Acc on train data : {}".format(training_data_acc))

Acc on train data : 0.8413793103448276


In [60]:
# Model Evaluation
# accuracy on test data
X_test_prediction = lg_model.predict(x_test)
test_data_acc = accuracy_score(X_test_prediction,y_test)


In [61]:
print("Acc on test data : {}".format(test_data_acc))

Acc on test data : 0.6666666666666666


In [63]:
import joblib
joblib.dump(lg_model,'lg_model.sav')
joblib.dump(dt_model,'dt_model.sav')
joblib.dump(rf_model,'rf_model.sav')
joblib.dump(sv_model,'sv_model.sav')
joblib.dump(nb_model,'nb_model.sav')
joblib.dump(kn_model,'kn_model.sav')


['kn_model.sav']

Makeing prediction system

In [64]:
input_data = (0.0293,0.0644,0.0390,0.0173,0.0476,0.0816,0.0993,0.0315,0.0736,0.0860,0.0414,0.0472,0.0835,0.0938,0.1466,0.0809,0.1179,0.2179,0.3326,0.3258,0.2111,0.2302,0.3361,0.4259,0.4609,0.2606,0.0874,0.2862,0.5606,0.8344,0.8096,0.7250,0.8048,0.9435,1.0000,0.8960,0.5516,0.3037,0.2338,0.2382,0.3318,0.3821,0.1575,0.2228,0.1582,0.1433,0.1634,0.1133,0.0567,0.0133,0.0170,0.0035,0.0052,0.0083,0.0078,0.0075,0.0105,0.0160,0.0095,0.0011)
#changing ininput data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = lg_model.predict(input_data_reshaped)
#print(prediction)

if (prediction[0] == 'R'):
  print('The Object is a Rock')
else:
  print('The Object is a Mine')

The Object is a Mine
